name: heatrates
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - alsa-lib=1.2.14
  - anyio=4.12.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.0.5
  - attr=2.5.2
  - attrs=25.4.0
  - aws-c-auth=0.9.1
  - aws-c-cal=0.9.10
  - aws-c-common=0.12.5
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.10.1
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.2
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.15.0
  - azure-storage-common-cpp=12.11.0
  - azure-storage-files-datalake-cpp=12.13.0
  - babel=2.17.0
  - beautifulsoup4=4.14.3
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - blosc=1.21.6
  - bokeh=3.8.1
  - bottleneck=1.6.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - cftime=1.6.4
  - charset-normalizer=3.4.4
  - click=8.3.1
  - climlab=0.9.1
  - climlab-cam3-radiation=0.3.1
  - climlab-emanuel-convection=0.3
  - climlab-rrtmg=0.4.1
  - climlab-sbm-convection=0.2
  - cloudpickle=3.1.2
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.14.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cytoolz=1.1.0
  - dask=2025.11.0
  - dask-core=2025.11.0
  - dbus=1.16.2
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - distributed=2025.11.0
  - double-conversion=3.3.1
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.0
  - fqdn=1.5.1
  - freetype=2.14.1
  - fsspec=2025.10.0
  - gflags=2.2.2
  - glog=0.7.1
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=12.2.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter=1.1.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.16
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.1
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarrow=22.0.0
  - libarrow-acero=22.0.0
  - libarrow-compute=22.0.0
  - libarrow-dataset=22.0.0
  - libarrow-substrait=22.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang-cpp21.1=21.1.6
  - libclang13=21.1.6
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.17.0
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libllvm21=21.1.6
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnetcdf=4.9.3
  - libnghttp2=1.67.0
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=22.0.0
  - libpciaccess=0.18
  - libpng=1.6.51
  - libpq=18.1
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libutf8proc=2.11.2
  - libuuid=2.41.2
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - locket=1.0.0
  - lz4=4.4.5
  - lz4-c=1.10.0
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mistune=3.1.4
  - msgpack-python=1.1.2
  - munkres=1.1.4
  - narwhals=2.12.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf4=1.7.3
  - nlohmann_json=3.12.0
  - notebook=7.5.0
  - notebook-shim=0.2.4
  - numpy=2.3.5
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.6.0
  - orc=2.2.1
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - parso=0.8.5
  - partd=1.4.2
  - patsy=1.0.2
  - pcre2=10.46
  - pexpect=4.9.0
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - pooch=1.8.2
  - prometheus-cpp=1.3.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=22.0.0
  - pyarrow-core=22.0.0
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyside6=6.9.3
  - pysocks=1.7.1
  - python=3.14.0
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-gil=3.14.0
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.14
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.9.3
  - re2=2025.11.05
  - readline=8.2
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.30.0
  - s2n=1.6.0
  - scipy=1.16.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.8
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - tblib=3.2.2
  - terminado=0.18.1
  - tinycss2=1.5.0
  - tk=8.6.13
  - tomli=2.3.0
  - toolz=1.1.0
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wayland=1.24.0
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - widgetsnbextension=4.0.15
  - xarray=2025.11.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xyzservices=2025.11.0
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
prefix: /home/as3675/.conda/envs/heatrates
